// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juarfxvgtivmbcslgyjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1YXJmeHZndGl2bWJjc2xneWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjQ1MDksImV4cCI6MjA1ODk0MDUwOX0.aorAZIaJ8-144jJlE9_hcoXPwxaowZL-TExQBmpu82A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);